services:
  - type: web
    name: cynara
    env: python
    buildCommand: "cd Flicks && pip install -r ../requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "cd Flicks && gunicorn Flicks.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "Flicks.settings"